CREATE TABLE mahasiswa (
npm INT(10) PRIMARY KEY,
nama_mahasiswa VARCHAR(30) NOT NULL,
email VARCHAR(40) NOT NULL,
id_user INT(10) NOT NULL,
kode_kelas VARCHAR(5) NOT NULL,
FOREIGN KEY (id_user) REFERENCES user(id_user) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (kode_kelas) REFERENCES kelas(kode_kelas) ON DELETE CASCADE ON UPDATE CASCADE);